---

- name: bobnet-bootstrap
  src: git@github.com:robyoung/bobnet-bootstrap-role.git
  scm: git
  version: master

- name: bobnet-configure
  src: git@github.com:robyoung/bobnet-configure-role.git
  scm: git
  version: master
